version: '3.8'
services:
  homelab-docs:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - REPO_URL=${REPO_URL:-https://github.com/llajas/homelab}
    ports:
      - "5000:80"
    environment:
      - REPO_URL=${REPO_URL:-https://github.com/llajas/homelab}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-120}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
